# Generated by Django 2.2.19 on 2021-04-05 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0050_auto_20201208_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store_email_stu_new',
        ),
        migrations.DeleteModel(
            name='store_email_teach_new',
        ),
        migrations.RemoveField(
            model_name='teacher_assignment_upload_file',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='teacher_assignment_upload_file',
            name='resource',
        ),
        migrations.AlterField(
            model_name='assignment_comments',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 20, 44, 8, 469091)),
        ),
        migrations.AlterField(
            model_name='student_submit_assignment_pro',
            name='attachment',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='attachment',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 5, 20, 44, 8, 453474)),
        ),
        migrations.AlterField(
            model_name='teacher_assignment_upload_file',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 5, 20, 44, 8, 453474)),
        ),
    ]
